// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  divider: dynamic(() => import('./Bar')),
  hero: dynamic(() => import('./Hero')),
  skills: dynamic(() => import('./Skills')),
};
